### ISSUE TITLE
Incorrect height calcualtion for multiline boxPropGrob

### ISSUE THREAD

**Issue by arcresu** [gforge/Gmisc#46] opened 2020-06-22 05:50 UTC
The height calculation for `boxPropGrob` is wrong when there are several lines of text. I've attempted to fix it, but I haven't succeeded in working out the problem so far. Multiline labels work fine for normal `boxGrob`s, so it might be something to do with the additional height of the "main" label. However, `boxPropGrob` also uses the `prConvTxt2Height` helper to calculate text height by counting lines and multiplying by the `lines` unit, whereas the normal `boxProp` just measures the height of the text grob directly.

Some other issues with `boxPropGrob`:

- I actually don't want to have that top/main label at all for my use case, but there doesn't seem to be any way to disable it. There's a check for `missing(label)` but it's not possible to call the function without `label`, and other parts of the function assume `label` is present.
- The `txt_gp`, `txt_left_gp`, `txt_right_gp` options are all ignored.
- There is no way to specify the justification of the text besides the text in the "main" label.

``` r
library(Gmisc)
#> Loading required package: Rcpp
#> Loading required package: htmlTable
library(grid)

grid.newpage()
boxPropGrob("Label", "Left1\nLeft2\nLeft3\nleft4", "Right", 0.5)
```

![](https://i.imgur.com/iDZBGMP.png)

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gforge** [comment] 2020-06-22 06:02
Excellent suggestions, I will look into it. Should be fixable.

**Comment by gforge** [comment] 2020-06-25 21:34
I think I got everything fixed, checkout the `bugfix/bad_prop_height` branch. I'm not that happy with the multiple txt_gp design, today I would usually try to use something like the style options that I've used in the htmlTable 2.0 update. What do you think?

**Comment by arcresu** [comment] 2020-06-26 00:49
Thanks for this! It seems to have solved the height calculation issue.

Unless I'm missing something obvious (I'm new to R, so quite possible), it's still not possible to call `boxPropGrob()` without providing a main label, since that's the first argument. E.g. I tried:
```r
> boxPropGrob(label_left="Left", label_right="Right", prop=0.5)
## Error in textGrob(label) : argument "label" is missing, with no default
```
Without changing the interface, I suppose it could accept `NULL` as a value for `label` (currently not allowed by the argument validation) and then replace `missing(label)` with `is.null(label)` checks?

About the text options, I agree that it would be nicer to separate content & formatting from layout. An nice interface might look something like:
```r
left_txt <- textGrob("Left", just = "left", gp = gpar())
left <- boxGrob(left_txt)
right_txt <- textGrob("Right", just = "right", gp = gpar())
right <- boxGrob(right_txt)
main_txt <- textGrob("Main", just = "centre", gp = gpar())
main <- boxGrob(main_txt)
boxPropGrob(left = left, right = right, main = main)
```
That's a lot more verbose, but now there's only one function to set the properties of each object, and the box functions overwrite the coordinates and dimensions of their children (if that's possible; I'm not familiar with how `grid` works). `boxPropGrob()` would only need options concerning the outside box and proportions rather than needing options to individually set `gp` and `just` on all 6 of its children.

**Comment by gforge** [comment] 2020-06-26 06:13
I think I've gotten the `missing` functionality working. There was some bad code that wasn't that well tested :grimacing:

**Comment by arcresu** [comment] 2020-06-26 06:35
Thanks again! I think that the important stuff is working now.

There's a minor cosmetic issue in that there's a bit too much padding on top when the main label is missing (and more padding in general than on `boxGrob`s):

``` r
library(Gmisc)
#> Loading required package: Rcpp
#> Loading required package: htmlTable
library(grid)

grid.newpage()
boxPropGrob(label_left="Left", label_right="Right", prop=0.5)
boxGrob("Single", y= 0.2)
boxPropGrob(label="Main", label_left="Left", label_right="Right", prop=0.5, y=0.8)
```

![](https://i.imgur.com/GzNBCa8.png)

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gforge** [comment] 2020-06-26 07:16
Yeah, I saw that but I had to run off with the kids to the pool 😏 I thin I know where the bug is. 

Regarding the arguments I think your suggestion becomes too verbose. In the htmlTable package I created a helper that was chainable, one option would be to hash a chain option where you have addLeftLabel() %>%addRightLabel() %>% boxPropGrob(prop=. 3), not sure if it's a gig idea though...

**Comment by gforge** [comment] 2020-06-26 16:56
Ok, I think the issue is fixed in the merged update. Going to work a little on the alignment feature that I'm adding.

Still thinking about the API change but that is beyond the scope of this issue and I'm not entirely sure that it will help new users to have the API in multiple functions. R's named arguments allows us to have a large number of arguments at a low cost, in `htmlTable` I changed it because it got hard to navigate through all the options but I don't think `boxPropGrob` is there yet, although as an author one quickly becomes blind to ones weird design choices... Feel free to comment here though if you have any thoughts.

**Closed by gforge** 2020-06-26 16:56 UTC

**Comment by arcresu** [comment] 2020-06-28 23:49
Thanks for your help with this, and for the package in general :)

About the API, I think if the choice is between keeping it in one function or splitting into 2, then having all the options in a single function is less confusing.

My main concern is that the interface then effectively has to duplicate (and keep up with) all of the options `grid` makes available on the underlying types or else it's restricting what can be done. The idea of my proposal above was to get around that by exposing the underlying objects (i.e. the `textGrob`s and `boxGrob`s) directly. `boxGrob` and `boxPropGrob` could be re-implemented with their current interface as high-level convenience wrappers around new functions that just do the layout. As a user you would start with those convenience wrappers, and if you find you need something fancy the interface doesn't support, you switch to the full flexibility of passing grobs to the layout functions. Anyway, just an idea.

**Comment by gforge** [comment] 2020-06-29 07:32
Yeah, I need to think about it. One way could be to have a `mergeBox` function that merges multiple boxes into one. I need to think about it a little more though...

Just finished the `align` and `spread` features, I think I'll push the new version within a week, unless I get a ton of CRAN issues. It would be great if you could have a look at the new vignette and see if there is something that is not that intuitive and needs more work.

**Comment by arcresu** [comment] 2020-06-30 00:50
The new features look very useful, and the vignette looks good to me!
